# Generated by Django 2.2.3 on 2019-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Keyword'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_art',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
