# Generated by Django 2.2.3 on 2019-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190703_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='keywords',
        ),
    ]
