# Generated by Django 2.2.3 on 2019-07-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190704_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
